### ISSUE TITLE
Cannot locate the required xls-file in pdok

### ISSUE THREAD

**Issue by Ton-O** [scubajorgen/TOP25OziGenerator#1]
First: thanks for this lifesaver!

I'm having some problems with finding the current xls-file in pdok. <=== solved, it's within the directory TOP25raster_Produktinformatie... (silly me)
Luckily, you have included your own csv-file on GitHub, so my issue is solved.
Still, it might be good to give some directions on:
- where to find the xls-file on the pdok-site
- how to actually RUN the java-file; I managed to do so, but I can see a lot of non-technical people putting aside this great solution, just because of that. (a simple: you need to have jdk installed (java is not enough), javac the java-file, then  exec the java-file)

**Comment by scubajorgen** [comment]
Thanx for the feedback. Yeah, it is a bit quick and dirty. I just published the code for those programmers doing similar. 
One of these days I'll tidy some things up and add more description.
The excel is in the Top25raster zip
For the moment I run the application from Netbeans

**Comment by scubajorgen** [comment]
Updated the code to make it more user friendly and extended the readme.MD
